[0m14:47:25.453979 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff712e22c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7111fda10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7114d62d0>]}


============================== 14:47:25.469388 | 8ddbe359-2732-44de-9b0e-67214cc2bb2d ==============================
[0m14:47:25.469388 [info ] [MainThread]: Running with dbt=1.8.3
[0m14:47:25.470242 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '../', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:48:04.402796 [debug] [MainThread]: Starter project path: /home/synev1/dev/data-warehouse/.venv/lib/python3.11/site-packages/dbt/include/starter_project
[0m14:48:04.408043 [info ] [MainThread]: 
Your new dbt project "datawarehouse" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:48:04.408695 [info ] [MainThread]: Setting up your profile.
[0m14:50:06.535893 [info ] [MainThread]: Profile datawarehouse written to ../profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:50:06.536773 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 161.12274, "process_user_time": 2.74865, "process_kernel_time": 0.170797, "process_mem_max_rss": "118956", "process_in_blocks": "1152", "process_out_blocks": "37240"}
[0m14:50:06.537251 [debug] [MainThread]: Command `dbt init` succeeded at 14:50:06.537171 after 161.12 seconds
[0m14:50:06.537566 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7111bc5d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff71121bf90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7ff7204b59d0>]}
[0m14:50:06.537891 [debug] [MainThread]: Flushing usage events
[0m16:42:44.890706 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fbf85a710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fbf853ad0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fbfbf9650>]}


============================== 16:42:44.896250 | 7b2f17c5-8c5a-4454-8720-0233badbd62d ==============================
[0m16:42:44.896250 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:42:44.897454 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '../', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m16:42:44.898948 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/synev1/dev/data-warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:42:44.900595 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.054065973, "process_user_time": 1.449091, "process_kernel_time": 0.169531, "process_mem_max_rss": "99512", "process_in_blocks": "140840", "process_out_blocks": "2032", "command_success": false}
[0m16:42:44.901063 [debug] [MainThread]: Command `dbt run` failed at 16:42:44.900975 after 0.06 seconds
[0m16:42:44.901395 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fbf9fd710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fcebb9a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8fbf859b10>]}
[0m16:42:44.901721 [debug] [MainThread]: Flushing usage events
[0m16:43:42.005560 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47a62710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47bfff50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47bffb50>]}


============================== 16:43:42.009641 | 67a93ecd-8119-4a3f-872a-cc5c99a68e12 ==============================
[0m16:43:42.009641 [info ] [MainThread]: Running with dbt=1.8.3
[0m16:43:42.010153 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '../', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m16:43:42.010626 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /home/synev1/dev/data-warehouse/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m16:43:42.012083 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.04241103, "process_user_time": 1.252392, "process_kernel_time": 0.126026, "process_mem_max_rss": "103852", "process_in_blocks": "140256", "process_out_blocks": "16", "command_success": false}
[0m16:43:42.012523 [debug] [MainThread]: Command `dbt run` failed at 16:43:42.012443 after 0.04 seconds
[0m16:43:42.012837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47a56d10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47a63810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8b47a57210>]}
[0m16:43:42.013150 [debug] [MainThread]: Flushing usage events
